src/apiv1/urls.py
from django.urls import path

from . import views

app_name = 'apiv1'

urlpatterns = [
    path(r'categories/', views.CategoriesListView.as_view(), name='categories-list'),
    path(r'offers/', views.OffersListView.as_view(), name='offers-list'),
]

src/goods/urls.py
from django.urls import path

from . import views

app_name = 'demo'

urlpatterns = [
    path('', views.DemoIndexView.as_view(), name='demo-index'),
    path('<slug:category_slug>/', views.DemoIndexView.as_view(), name='browse-category')
]

src/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from goods import views

urlpatterns = [
    path('ga/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('demo/', include('goods.urls')),
    path('api/v1/', include('apiv1.urls')),
] + static(settings.STATIC_URL, document_root=settings.BASE_DIR)

templates/index.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Hi</title>

</head>

<body>
  <h1>Привет, разработчик!</h1>
  <p>На ресурсы API можно заходить браузером, а можно
    curl-ом или бибилиотекой какой. Формат выдачи зависит
    от HTTP-заголовка Accept.
    Поддерживается text/html (для просмотра браузером)
    и application/json (для вызова из кода или командной строки).
  2</p>
  <h3>Методы API:</h3>
  <p>просмотр категорий:
    <a href="{% url 'apiv1:categories-list' %}">{% url 'apiv1:categories-list' %}</a>
  </p>
  <p>поиск товаров:
    <a href="{% url 'apiv1:offers-list' %}">{% url 'apiv1:offers-list' %}</a>
  </p>
  <h3>Демка:</h3>
  <p>что хотели получить:
    <a href="{% url 'demo:demo-index' %}">{% url 'demo:demo-index' %}</a>
  </p>
</body>
</html>